version: '2'
services:
  web:
    image: navee-hari/web:latest
    build: ./apps/web
    ports:
      - "$PORT:8080"
    command: "twistd --nodaemon --python=quote_http.py"
    volumes:
      - ./apps/web:/apps/web
